### ISSUE TITLE
API level 32 is Android 12L, not Android 13.

### ISSUE THREAD

**Issue by bc-lee** [ebelinski/apilevels#8]
See https://developer.android.com/about/versions/12/12L/overview for details.

**Comment by ebelinski** [comment]
Good catch @bc-lee. I updated the row to list Android 12L instead of Android 13. I wonder though, is Android 12L just a marketing term for Android 12.1? I see the L in 12L refers to "large" screens, but it seems that 12L can also be installed on Google Pixel so I'm not sure what the versioning/numbering strategy will be here.

**Comment by bc-lee** [comment]
I'm not a Google Insider, so I don't know for sure, but looking at the description, it seems to be a déjà vu of Android 4.4W (API level 20). As with API level 20, the difference in public APIs between [API levels 31 and 32](https://developer.android.com/sdk/api_diff/32/changes) is very small. The difference between the public APIs between [API levels 26 (O) and 27 (O_MR1)](https://developer.android.com/sdk/api_diff/27/changes) is much greater than that in API level 32. So, I think Google is releasing it without even a minor version upgrade.
Note that Android 12L (API level 32) uses 'Build.VERSION_CODES.S_V2', not 'T'.

**Comment by ebelinski** [comment]
I see, thanks @bc-lee! I updated the website, please let me know if there are any additional changes I should make. I combined the Android 12 and 12L rows with the correct version codes now and added back a separate Android 13 row with T/Tiramisu.

**Comment by bc-lee** [comment]
I don't think we need to change it right now. Thank you!
